# Generated by Django 5.2.7 on 2025-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
